#端口号
#server:
#  port: 8006
spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://101.133.224.127:3306/guli_cms?serverTimezone=GMT%2B8
#    username: root
#    password: 11111111
#    hikari:
#      connection-test-query: SELECT 1
#      connection-timeout: 60000
#      idle-timeout: 500000
#      max-lifetime: 540000
#      maximum-pool-size: 12
#      minimum-idle: 10
#      pool-name: GuliHikariPool
  #      json返回的时间字段转换
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  #    nacos的注册中心
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
  #redis配置
  redis:
    host: 101.132.35.66
    port: 6379
    password: xiaohu
    database: 0
    timeout: 120000
    lettuce:
      pool:
        max-idle: 5
        min-idle: 0
        max-active: 20
        max-wait: -1
  #        链路追踪
#  zipkin:
#    base-url: http://49.233.148.75:9411
#    #    防止springcloud把zipkin也给注册到注册中心
#    discovery-client-enabled: false
#    sender:
#      type: web
#    sleuth:
#      sampler:
#        probability: 1  #全量记录

#mybatis-plus:
#  configuration: #mybatis的日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    #配置mapper xml文件的路径
#  mapper-locations: classpath:xml/*.xml
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
